### ISSUE TITLE
Validación de propuesta de valor

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-egal#2]
[Practica 1__Validación de propuesta de valor..pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-egal/files/6137826/Practica.1__Validacion.de.propuesta.de.valor.pdf)

**Comment by Nancy2050** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
