### ISSUE TITLE
Práctica de costos

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-egal#3]
[Práctica de Costos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-egal/files/6137830/Practica.de.Costos.pdf)

**Comment by josealfredo79** [comment]
Los costos para los sistemas de computo son de 80,000 estab muy elevado, deben verificar...

**Comment by Nancy2050** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
